### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [cjwirth/awesome-ios-ui#1]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction - the awesome repo owners need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource?

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

Some thoughts on this:
1. you don't use any stars or traction with your forks, github handles the change.
2. you would still be the owner!
3. by being amongst other awesome repos, you're repo will get more visibility.
4. we would have admins of your choice on deck, in the case you can no longer support we can ensure your project lives on.

**Comment by cjwirth** [comment]
I'll wait and see what some other projects do, first... It doesn't really seem like anyone is moving over.

On another note, it might be a good idea to follow the awesome-list naming convention, ie using-kebab-case rather than CamelCase
