### ISSUE TITLE
CBZSplashView - Transition

### ISSUE THREAD

**Issue by callumboddy** [cjwirth/awesome-ios-ui#10]
Hi mate any change you could get mine put in the transitions section?

https://github.com/callumboddy/CBZSplashView

let me know,

cheers

**Comment by reejosamuel** [comment]
add it yourself and send a pull request.

**Comment by cjwirth** [comment]
Gotcha buddy 
329edd8a2bf9cac5183077a4a50134300ebe8051

**Comment by callumboddy** [comment]
haha, thanks mate
