### ISSUE TITLE
Missing Onboarding Libraries

### ISSUE THREAD

**Issue by suhitp** [cjwirth/awesome-ios-ui#14]
can you add Onboarding section where you can add some Onboarding libraries like

https://github.com/mamaral/Onboard
https://github.com/MosheBerman/Surfboard
https://www.cocoacontrols.com/controls/eaintroview
https://www.cocoacontrols.com/controls/abcintroview

**Comment by cjwirth** [comment]
Yeah, these are neat. Might get its own section.

**Comment by skywinder** [comment]
+1 to this section and +1 Library:
https://github.com/MatthewYork/MYBlurIntroductionView

**Comment by skywinder** [comment]
And +1 another awesome animate onboarding:

https://github.com/IFTTT/JazzHands

**Comment by cjwirth** [comment]
Hey, I added the ones that I thought were awesome. 
97d0033abdab439adc911b3f2c2cdf729154bc30

**Comment by ealeksandrov** [comment]
@cjwirth MYBlurIntroductionView is unmaintained now and shows warning that Apple ban its old technique of blurring.
