### ISSUE TITLE
Add Calendars section

### ISSUE THREAD

**Issue by skywinder** [cjwirth/awesome-ios-ui#18]
Looking for a calendars implementation. Let's collect this libraries.

1. https://github.com/jonathantribouharet/JTCalendar 

![](https://github.com/jonathantribouharet/JTCalendar/blob/master/Screens/example.gif)

2. https://github.com/f33chobits/FSCalendar 

![](https://cloud.githubusercontent.com/assets/5186464/6652191/f11d5242-caa1-11e4-9cc2-8a7c0cc9ef02.gif)

**Comment by skywinder** [comment]
Here is another nice library.
I'm thinking it's really missed section!

https://github.com/Glow-Inc/GLCalendarView

![demo](https://cloud.githubusercontent.com/assets/3356474/8494158/f1fcb0ac-216a-11e5-8206-f5502f63fe6d.gif)

**Comment by cjwirth** [comment]
I do like that last one! Calendars and good date pickers are definitely something people need, and are annoying to write yourself.

Currently I don't have internet at home, and I can't really spend time at work doing this, but I'll see if I can find enough to make a section out of.

**Comment by cjwirth** [comment]
I agree, date pickers and calendars are something that are pretty annoying to make yourself. I'm going to give this whole list a review, and update it. I've added these to the section for potential calendars.
