### ISSUE TITLE
Missing 3rd party keyboards section

### ISSUE THREAD

**Issue by nurne** [cjwirth/awesome-ios-ui#2]
iOS8 introduced 3rd party keyboards support as part of its extensibility APIs
There are many projects for this and I'd be happy to see them here

**Comment by cjwirth** [comment]
This is something I hadn't even considered! Let me take a look and see if I can find any awesome keyboards. Do you have any favorites?

**Comment by cjwirth** [comment]
I don't know of any awesome keyboards, but I'm going to be giving this whole list another look-over, so I'll keep an eye out for keyboards!
