### ISSUE TITLE
Which section in README should I suggest/contribute to for an animated UI button

### ISSUE THREAD

**Issue by tandavas** [cjwirth/awesome-ios-ui#21]
I would like to make a pull request for one of my open source project -- [HTPressableButton](https://github.com/herinkc/HTPressableButton), an animated flat design pressable button, to [awesome-creator](https://github.com/cjwirth/awesome-creator), but I'm not entirely sure which section will fit with the animated buttons.

Which section should I add  [HTPressableButton](https://github.com/herinkc/HTPressableButton) to?

Some demo for you to see:

![HTPressableButton](https://raw.github.com/herinkc/HTPressableButton/master/READMEImages/RectButtonImage.gif)
![HTPressableButton](https://raw.github.com/herinkc/HTPressableButton/master/READMEImages/RoundedRectButtonImage.gif)
![HTPressableButton](https://raw.github.com/herinkc/HTPressableButton/master/READMEImages/CircularButtonImage.gif)

**Comment by cjwirth** [comment]
That is a good question.

When I originally started making this list, I actually did have a "Buttons" section, but depending on where I was drawing the level of what I considered "awesome," I either had way too many or not enough to warrant a section.

So I guess it's be OK to have a "Buttons" section. Or maybe "Controls" to incorporate more than just buttons?

**Comment by cjwirth** [comment]
It's been over a half a year since I made this list. Thinking about going through and reviewing the list and adding/removing some repos. I'll add this to the list. Maybe I'll have a buttons or components section.
