### ISSUE TITLE
Additions

### ISSUE THREAD

**Issue by dkhamsing** [cjwirth/awesome-ios-ui#24]
https://github.com/andreamazz/UITextField-Shake

![screenshot](https://cloud.githubusercontent.com/assets/4723115/7737887/c8adebd2-ff03-11e4-8c68-2beb9ef60f1d.gif)

https://github.com/ninjaprox/NVActivityIndicatorView
![](https://raw.githubusercontent.com/ninjaprox/NVActivityIndicatorView/master/Demo.gif)

**Comment by cjwirth** [comment]
Added these to the `development` branch, will merge them after I get some other stuff taken care of :+1:
