### ISSUE TITLE
404

### ISSUE THREAD

**Issue by dkhamsing** [cjwirth/awesome-ios-ui#30]
FYI this link is broken 
    http://gh-btns.cjwirth.com/stars/Yalantis/FoldingTabBar.iOS
![](http://gh-btns.cjwirth.com/stars/Yalantis/FoldingTabBar.iOS)

**Comment by cjwirth** [comment]
Yeah I know... There are problems with the service to create the images.
The problem has to do with the period in the repo name. Closing this issue because it's a known issue in https://github.com/cjwirth/github-buttons-1
