### ISSUE TITLE
Feature request:Add  a table column to tell the source in Objective-C or Swift

### ISSUE THREAD

**Issue by ryh** [cjwirth/awesome-ios-ui#4]
Feature request:Add  a table column to tell the source in Objective-C or Swift (and the swift version ).
Please. :smile:

**Comment by cjwirth** [comment]
Oooh, this is a pretty neat idea!

I have a script that I use to generate the files, so it might take a little bit of time to tweak my data model to support this, but I really like the idea :+1:

**Comment by TolgaB** [comment]
I can do this, ill push later today.

**Comment by cjwirth** [comment]
b90c1cabdbef6d81746505b61fdaba5175e53c7a
I thought more columns was making it quite, so I put repo metadata all in the same column, with the demo in another

**Comment by lovemyboo** [comment]
G
