### ISSUE TITLE
How to clone all git repositories?

### ISSUE THREAD

**Issue by Wang-Jong** [cjwirth/awesome-ios-ui#57]
I want to clone all iOS UI/UX libraries (git repositories) contained in this repository automatically.
How can I do it?
Any help would be appreciated.
Thanks.

**Comment by charlymr** [comment]
Open terminal, go to the folder for all your repo and paste this:
``` bash
mkdir awesome-ios-ui
cd awesome-ios-ui

curl https://raw.githubusercontent.com/cjwirth/awesome-ios-ui/master/README.md \
| grep -Eo "((https)://github.com/[a-zA-Z0-9./?=_-]*/[a-zA-Z0-9./?=_-]*/)" \
| sort | uniq  | xargs -n 1 git clone
```

**Comment by Wang-Jong** [comment]
It works!
Thanks, charlymr.
May I ask you one more?
Is there any way to download all projects instead of git cloning by its index-structure?

**Comment by charlymr** [comment]
What you ask is too much more complicated as the Download URL for each repo is not available on the readme page, so the regex won't do to extract the git repo URLs.

You could add a lin in your script to clean up all git references after:
```bash
mkdir awesome-ios-ui
cd awesome-ios-ui

curl https://raw.githubusercontent.com/cjwirth/awesome-ios-ui/master/README.md \
| grep -Eo "((https)://github.com/[a-zA-Z0-9./?=_-]*/[a-zA-Z0-9./?=_-]*/)" \
| sort | uniq  | xargs -n 1 git clone

### Be careful with this as we assume we are in the directory awesome-ios-ui
rm -rf */.git*
```

**Comment by Wang-Jong** [comment]
I see.
Thank you for your kind explanation.
